### ISSUE TITLE
Notify on absent 'wezterm' executable

### ISSUE THREAD

**Issue by thomasmore** [willothy/wezterm.nvim#1]
Should plugin somehow check if `wezterm` executable is available in $PATH?

A bit of context: I am working in WSL and my executable is available as `wezterm.exe`. Everything is perfectly fine if I add `wezterm` symlink to `wezterm.exe`, but it required a bit of investigation on my side. Also would you mind supporting WSL out of the box? I could make a PR if you are ok with this.

**Comment by willothy** [comment]
Definitely would be open to a PR - I also use wsl some of though, so I'll look into supporting it out of the box as well.

Thanks!
