### ISSUE TITLE
(Not an issue) What is that sidepane on the right of your demo? 

### ISSUE THREAD

**Issue by rkabrick** [willothy/wezterm.nvim#11]
Hey! Great work with this plugin... Wondering what that awesome looking side pane thing with the date/time/todos/etc is in your config. Is that neovim, tmux, wezterm, or something else?

**Comment by willothy** [comment]
I think that's [sidebar.nvim](https://github.com/sidebar-nvim/sidebar.nvim) - it's modular (similar to statusline/tabline plugins) so you can choose which sections you want, or implement your own.
