### ISSUE TITLE
split_pane doesn't work

### ISSUE THREAD

**Issue by tj-moody** [willothy/wezterm.nvim#9]
Running split_pane in any way doesn't work. For example:

```
:lua require('wezterm').split_pane.vertical()
```
results in the following error:
<img width="1070" alt="Screenshot 2023-11-02 at 11 53 15 AM" src="https://github.com/willothy/wezterm.nvim/assets/92702993/d0a29cc7-f7e0-4fa4-9699-677658adcc22">

I'm passing no configuration to wezterm (`config = true` in lazy), and the same error still happens when I don't load any other plugins.

**Comment by willothy** [comment]
Thanks for reporting, I'll fix this ASAP
